# Generated by Django 4.2.9 on 2024-02-21 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_alter_product_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ("name",),
                "verbose_name": "category",
                "verbose_name_plural": "categories",
            },
        ),
    ]
