# Generated by Django 4.1 on 2024-02-23 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0004_alter_category_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="cart",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="product",
        ),
        migrations.DeleteModel(
            name="Cart",
        ),
        migrations.DeleteModel(
            name="CartItem",
        ),
    ]
